version: @version@
message_prefix: "&6[CA]"
messages:
  common:
    noPermission: "&cYou do not have permission to use this command."
    notPlayer: "&cYou need to be a player to use this command."
    notImplemented: "&cNot yet implemented!."
    argLengthMismatch_Ignoring: "&eFound &6{0}&e arguments, but was expecting &6{1}&e, ignoring arguments."
    argLengthMismatch: "&cFound &4{0}&c arguments, but was expecting &4{1}&c."
    argLengthMin: "&cFound &4{0}&c arguments, but was expecting at least &4{1}&c."
  calist:
    noCommandsForItem: "&cNo commands for item &4{0}&c."
    foundCommandForItem: "&aFound command for item &2{0}&a:\nID: &2{1}&a\nCommand: &2{2}"
  caremove:
    invalidID: "&cInvalid id &4{0}&c."
    couldntFindCommand: "&cCould not find command with id &4{0}&c."
    success: "&aRemoved successfully:\nMaterial: &2{0}&a\nID: &2{1}&a\nCommand: &2{2}"
  careload:
    success: "&aSuccessfully reloaded config."
    invalidConfigOption: "&cInvalid configuration value at &4{0}&c."
  ca:
    invalidBoolean: "&cInvalid argument &4{0}&c.\nWas expecting one of [yes,y,true,t,no,n,false,f]."
    success: "&aSuccessfully bound command."
    templateMismatchedBraces: "&cMismatched braces."
    templateInvalidPlaceholder: "&cInvalid placeholder &4{0}&c."